import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "react-slideshow-image/dist/styles.css";
import { useEffect } from "react";
import GlideComponent from "../components/glide/GlideComponent";
import BigGlide from "../components/bigGlide/BigGlide";
import SecGlide from "../components/glide/SecGlide";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>AVIV SHAMIR art galery</h1>
      <BigGlide />
      <div>
        <h3>collections</h3>
        <GlideComponent id="1" />
      </div>
      <div>
        <h3>costume portrates</h3>
        <SecGlide id="2" />
      </div>
      <main className={styles.main} />
    </div>
  );
}
